### PR TITLE
Fix save study with empty fields

### LINKED ISSUE #15: Fix saving a study with no title & empty question
### **Context**
Currently, the app lets you save a study without a title & with an empty question.

### **Expected outcome**
The user **should not be able** to save an "empty" study.

### Scenarios
**Given** the user is on the edit study page
**And** the study has
- a title
- a variable number of questions with title & answer
- an empty question

**When** the user publishes or saves as draft the current study
**Then** the update to the study should not contain the empty question

---

**Given** the user is on the edit study page
**And** the study has
- a title
- one or more questions that have only title

**When** the user publishes or saves as draft the current study
**Then** the update to the study should contain the question(s) that have only titles

Note: keep in mind that we need to edit/change the logic in the React about the index value.

### PR DESCRIPTION
**Pull request by srzvan**
Closes #15

### CODE REVIEW

**Comment by razvan-thinslices** [comment]
> @razvan-thinslices, what should the app do in the following scenario: **Given** the user is on the create/edit study page **And** the study has
> 
> * title
> * variable number of "complete" questions (with title & answer)
> * and one question that has only answer
> 
> **When** the user saves the study **Then** ...
> 
> **Options**
> 
> * display validation error that you have a question with answer, but no title
> * display modal that gives the user two options - _Continue_ & _Cancel_
>   
>   * _Continue_ will save the study & discard the incomplete question
> * profit?

As @electronrecord described the desired flow is to first add the questions and only then go to adding answers to these questions. For now, we can either leave the logic as is, and also save "questions" that only have answers. Another option is to display the answer field only when the question field is not empty (this can be exploited).

But mainly, it's outside of the scope of this issue and we would tackle the problem when reworking the create / edit study flow

File: src/components/Button/Button.tsx [hunk 1]
```diff
@@ -8,10 +8,11 @@ type ButtonProps = {
   href?: string;
   className?: string;
   onClick?: () => void;
+  isDisabled?: boolean;
```
Comment (razvan-thinslices) [inline src/components/Button/Button.tsx:11]:
```suggestion
  disabled?: boolean;
```

**Review by razvan-thinslices — APPROVED** [review]

**Review by razvan-thinslices — APPROVED** [review]
